import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from './Card';
import { Badge } from './Badge';
import { Button } from './Button';
import { Rating } from './Rating';
export const ProductCard = ({ image, name, price, originalPrice, discount, rating, reviewCount, inStock, onAddToCart, onViewDetails, className, }) => {
    return (_jsxs(Card, { hover: true, className: `p-4 overflow-hidden ${className || ''}`, children: [_jsxs("div", { className: "relative mb-4 h-40 overflow-hidden rounded bg-gray-100", children: [_jsx("img", { src: image, alt: name, className: "w-full h-full object-cover transition-transform duration-300 hover:scale-105" }), discount && (_jsx("div", { className: "absolute top-2 right-2", children: _jsxs(Badge, { variant: "danger", children: [discount, "% OFF"] }) })), !inStock && (_jsx("div", { className: "absolute inset-0 bg-black/50 rounded flex items-center justify-center", children: _jsx("span", { className: "text-white font-semibold", children: "Out of Stock" }) }))] }), _jsx("h3", { className: "font-semibold text-base mb-2 line-clamp-2 text-gray-900 hover:text-green-600 transition-colors cursor-pointer", onClick: onViewDetails, children: name }), _jsx("div", { className: "mb-3 flex items-center gap-1", children: _jsx(Rating, { value: rating, readonly: true, count: reviewCount }) }), _jsxs("div", { className: "mb-4 flex items-center gap-2", children: [_jsxs("span", { className: "text-lg font-bold text-green-600", children: ["$", price] }), originalPrice && (_jsxs("span", { className: "text-sm text-gray-500 line-through", children: ["$", originalPrice] }))] }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { variant: "primary", size: "md", fullWidth: true, disabled: !inStock, onClick: onAddToCart, className: "text-sm", children: "Add to Cart" }), _jsx(Button, { variant: "outline", size: "md", onClick: onViewDetails, className: "text-sm", children: "View" })] })] }));
};
ProductCard.displayName = 'ProductCard';
